move pr cleanup to publish action and reorder; remove comments from actions that don't apply anymore
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>

diff --git a/.github/workflows/build-asciidoc.yml b/.github/workflows/build-asciidoc.yml
--- a/.github/workflows/build-asciidoc.yml
+++ b/.github/workflows/build-asciidoc.yml
@@ -13,6 +13,8 @@ on:
   push:
     branches: 
     - main
+    - rhdh-1.**
+    - 1.**.x
 
 jobs:
   adoc_build:
@@ -35,30 +37,11 @@ jobs:
         # install 
         sudo apt-get -y -q install asciidoctor && asciidoctor --version
         echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
-        echo "Building branch ${{ env.GIT_BRANCH }}"
-
-    - name: Check branch name
-      run: |
-        echo "Building branch ${{ env.GIT_BRANCH }}"
-
-    - name: remove merged PR branches 
-      run: |
-        git config user.name "rhdh-bot service account"
-        git config user.email "rhdh-bot@redhat.com"
-
-        git checkout gh-pages
-        for d in $(find . -maxdepth 1 -name "pr-*" -type d); do 
-          echo -n "Check merge status of PR ${d/pr-/} ... "
-          curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.RHDH_BOT_TOKEN }}" ${{ GITHUB_API_URL }}/repos/${{ GITHUB_REPOSITORY }}/pulls/$PR | grep merged\"
-        done
-        # git commit -s -m "remove merged PR branches" .
-        # git push origin gh-pages
-        git checkout ${{ env.GIT_BRANCH }}
 
     - name: Build guides and indexes
       run: |
         echo "Building branch ${{ env.GIT_BRANCH }}"
-        build/scripts/build.sh -b main
+        build/scripts/build.sh -b ${{ env.GIT_BRANCH }}
 
     # repo must be public for this to work
     - name: Deploy
@@ -68,6 +51,26 @@ jobs:
         github_token: ${{ secrets.RHDH_BOT_TOKEN }}
         publish_branch: gh-pages
         keep_files: true
-        publish_dir: ./titles-generated # /main
-        # destination_dir: ./${{ env.GIT_BRANCH }}
-        # TODO regenerate the root index.html
+        publish_dir: ./titles-generated
+
+    - name: Cleanup merged PR branches 
+      run: |
+        PULL_URL="https://api.github.com/repos/redhat-developer/red-hat-developers-documentation-rhdh/pulls"
+        GITHUB_TOKEN="${{ secrets.RHDH_BOT_TOKEN }}"
+        git config user.name "rhdh-bot service account"
+        git config user.email "rhdh-bot@redhat.com"
+
+        git checkout gh-pages; git pull || true
+        for d in $(find . -maxdepth 1 -name "pr-*" -type d); do 
+          PR="${d#*pr-}"
+          echo -n "Check merge status of PR $PR ... "
+          if [[ $(curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "$PULL_URL/$PR" | grep merged\") == *"merged\": true"* ]]; then
+            echo "merged, can delete from pulls.html and remove folder $d"
+            git rm -fr --quiet $d
+            sed -r -e "/pr-$PR\/index.html>pr-$PR</d" -i pulls.html
+          else
+            echo "PR is unmerged (or could not read API)"
+          fi
+        done
+        git commit -s -m "remove merged PR branches" .
+        git push origin gh-pages
