tweaks to make api check work
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -43,13 +43,21 @@ jobs:
     - name: remove merged PR branches 
       run: |
         PULL_URL="https://api.github.com/repos/redhat-developer/red-hat-developers-documentation-rhdh/pulls"
+        GITHUB_TOKEN="${{ secrets.RHDH_BOT_TOKEN }}"
         git config user.name "rhdh-bot service account"
         git config user.email "rhdh-bot@redhat.com"
 
-        git checkout gh-pages
+        git checkout gh-pages; git pull || true
         for d in $(find . -maxdepth 1 -name "pr-*" -type d); do 
-          echo -n "Check merge status of PR ${d#*pr-} ... "
-          curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.RHDH_BOT_TOKEN }}" $PULL_URL/$PR | grep merged\"
+          PR="${d#*pr-}"
+          echo -n "Check merge status of PR $PR ... "
+          if [[ $(curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "$PULL_URL/$PR" | grep merged\") == *"merged\": true"* ]]; then
+            echo "merged, can delete from pulls.html and remove folder $d"
+            # git rm -fr --quiet $d
+            # sed -r -e "/pr-$PR\/index.html>pr-$PR</d" -i pulls.html
+          else
+            echo "PR is unmerged (or could not read API)"
+          fi
         done
         # git commit -s -m "remove merged PR branches" .
         # git push origin gh-pages
